version: "3"
services:
  hub:
    image: selenium/hub:latest
  chrome:
    image: selenium/node-chrome:latest
    shm_size: '2g'
    depends_on: 
    - hub
    deploy:
      replicas: 2
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
  firefox:
    image: selenium/node-firefox:latest
    shm_size: '2g'
    depends_on: 
    - hub
    deploy:
      replicas: 2
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
  vendor-portal:
    image: dopitek2012/selenium-docker:latest
    depends_on:
    - hub
    - chrome
    - firefox
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=4
    - TEST_SUITE=vendor-portal.xml
    volumes:
    - /d/dockerWorkspace/05-dockerize/02-grid-and-test-suites/vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
    image: dopitek2012/selenium-docker:latest
    depends_on:
    - hub
    - chrome
    - firefox
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub
    - THREAD_COUNT=4
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - /d/dockerWorkspace/05-dockerize/02-grid-and-test-suites/flight-reservation:/home/selenium-docker/test-output  